<?php
/**
 * Created by PhpStorm.
 * User: lqj
 * Date: 2017/9/19
 * Time: 下午9:08
 */

namespace yii2tags;


use yii\helpers\Html;
use yii\widgets\InputWidget;
use yii\helpers\Json;

class TagsInputWidgetX  extends InputWidget
{
    public $options = ['class' => 'form-control'];
    public $clientOptions = [];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->clientOptions['tagClass']='label label-success';
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        echo Html::activeInput('text', $this->model, $this->attribute, $this->options);
        TagsInputAssetX::register($this->view);
        $this->registerScript();
        $this->registerEvent();
    }

    protected function registerScript()
    {
        $clientOptions = empty($this->clientOptions) ? '' : Json::encode($this->clientOptions);
        $js = "jQuery('#{$this->options["id"]}').tagsinput({$clientOptions});";
        $this->getView()->registerJs($js);
    }

    protected function registerEvent()
    {
        if (!empty($this->clientEvents)) {
            $js = [];
            foreach ($this->clientEvents as $event => $handle) {
                $js[] = "jQuery('#{$this->options["id"]}').on('$event',$handle);";
            }
            $this->getView()->registerJs(implode(PHP_EOL, $js));
        }
    }

}