<?php
/**
 * Created by PhpStorm.
 * User: lqj
 * Date: 2017/9/19
 * Time: 下午9:08
 */

namespace yii2tags;


use yii\widgets\InputWidget;

class TagsInputWidgetX  extends InputWidget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        echo 'sdfsdf';
    }

}